import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='h-screen flex justify-center items-center bg-slate-800'>
          <div
            className='p-4 border rounded bg-white'
            style={{ minWidth: '400px' }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
